# Development version of the beyla Dockerfile that compiles for coverage
# and allows retrieving coverage files.
# The production-ready minimal image is in the project root's dockerfile.
FROM golang:1.26.2@sha256:1e598ea5752ae26c093b746fd73c5095af97d6f2d679c43e83e0eac484a33dc3 AS builder

ARG TARGETARCH

ENV GOARCH=$TARGETARCH

WORKDIR /

COPY internal/test/integration/components/obi/ebpf_instrument_wrapper.sh /ebpf_instrument_wrapper.sh

WORKDIR /src

# Copy the go manifests and source
COPY .git/ .git/
COPY bpf/ bpf/
COPY cmd/ cmd/
COPY pkg/ pkg/
COPY go.mod go.mod
COPY go.sum go.sum
COPY Makefile Makefile

# Build
RUN make compile-for-coverage

FROM scratch

# Copy the native executable into the containers
COPY --from=builder /src/bin/obi /obi
COPY --from=builder /ebpf_instrument_wrapper.sh /ebpf_instrument_wrapper.sh

WORKDIR /

ENTRYPOINT [ "/ebpf_instrument_wrapper.sh" ]
