FROM python:3.14@sha256:4bdca440e7381ba0d706e3718714c1a4cde97b460d8411c1af9c704bba1fba0f
EXPOSE 8391

WORKDIR /app

COPY internal/test/integration/components/pythonasync-uvloop/requirements-3.9.txt .
RUN pip install --require-hashes -r requirements-3.9.txt

COPY internal/test/integration/components/pythonasync-uvloop .

CMD ["python", "async_context_test.py"]
