FROM ruby:4.0.3@sha256:ebd9bbec4962e1ed9ae266b6dd89fe183a6f748ef71ddbfd76994e91f13f62ad AS builder

WORKDIR /build

ENV BUNDLE_PATH=/usr/local/bundle

COPY internal/test/integration/components/rubytestserver/testapi .
COPY internal/test/integration/components/rubytestserver/testapi_compat/Gemfile_ruby302_puma5 Gemfile
COPY internal/test/integration/components/rubytestserver/testapi_compat/Gemfile_ruby302_puma5.lock Gemfile.lock

RUN gem install bundler -v 2.2.22
RUN bundle _2.2.22_ install
RUN bundle exec rake app:update:bin
RUN bundle exec rake db:migrate

FROM ruby:4.0.3-slim@sha256:198547d3216e0efe6fb337997f22fa98eef4270b38033a697dad148d9d8b9b0d

WORKDIR /

ENV BUNDLE_PATH=/usr/local/bundle

COPY --from=builder /build .
COPY --from=builder /usr/local/bundle /usr/local/bundle

EXPOSE 3040

CMD [ "bundle", "exec", "rails", "server", "-p", "3040", "-b", "0.0.0.0" ]
